# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-11 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='goods',
            table='axf_goods',
        ),
    ]
