# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-12 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0004_auto_20190312_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='axf', max_length=100),
        ),
    ]
